version: '2'

services:

  mariadb:
    image: enclaive/mariadb-sgx:latest
    build: .
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - type: volume
        target: /data
    ports:
      - "3306:3306"
